name: dd
channels:
  - pytorch
  - nvidia
  - defaults
dependencies: 
  - git
  - python
  - pip
  - pytorch
  - pytorch-cuda
  - torchvision
  - torchaudio
  - setuptools
  - pip:
    - -e .
    - v-diffusion-pytorch
    - k-diffusion
    - PySoundFile
    - black
    - diffusers
variables:
  TRANSFORMERS_OFFLINE: 1
  HF_DATASETS_OFFLINE: 1